apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260507-234625-q00tljyrmugw-service
spec:
  selector:
    app: enterprise-system-20260507-234625-q00tljyrmugw
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
